# Generated by Django 3.2 on 2021-04-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='title',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='title',
            new_name='size',
        ),
    ]
